language: ruby
env:
  - CI=true
before_script:
  - "bundle exec rake db:prepare"
rvm:
  - 2.0.0
  - 2.1.6
  - 2.2.2
  - 2.3.1
gemfile:
  - gemfiles/rails32.gemfile
  - gemfiles/rails4.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails5.gemfile
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails5.gemfile
    - rvm: 2.1.6
      gemfile: gemfiles/rails5.gemfile
tifications:
  recipients:
    - gabriel.sobrinho@gmail.com
    - thiago.pradi@gmail.com
