language: ruby
env:
  - CI=true
before_script:
  - "bundle exec rake db:prepare"
rvm:
  - 2.2.5
  - 2.3.1
gemfile:
  - gemfiles/rails4.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
notifications:
  recipients:
    - gabriel.sobrinho@gmail.com
    - thiago.pradi@gmail.com
