mysql: &mysql
  adapter: mysql
  host: localhost

octopus:
  shards:
    alone_shard:
      database: octopus_shard5
      <<: *mysql

    postgresql_shard:
      adapter: postgresql
      username: <%= ENV['POSTGRES_USER'] || 'postgres'%>
      password:
      database: octopus_shard1
      encoding: unicode

    sqlite_shard:
      adapter: sqlite3
      database: /tmp/database.sqlite3

    history_shards:
      aug2009:
        database: octopus_shard2
        <<: *mysql
      aug2010:
        database: octopus_shard3
        <<: *mysql
      aug2011:
        database: octopus_shard4
        <<: *mysql

    country_shards:
      canada:
        database: octopus_shard2
        <<: *mysql
      brazil:
        database: octopus_shard3
        <<: *mysql
      russia:
        database: octopus_shard4
        <<: *mysql


production_raise_error:
  shards:
    history_shards:
      duplicated_shard_name:
        database: octopus_shard5
        <<: *mysql

    country_shards:
      duplicated_shard_name:
        database: octopus_shard4
        <<: *mysql

production_replicated:
  replicated: true
  fully_replicated: false

  shards:
    slave1:
      database: octopus_shard2
      <<: *mysql
    slave2:
      database: octopus_shard3
      <<: *mysql
    slave3:
      database: octopus_shard4
      <<: *mysql
    slave4:
      database: octopus_shard5
      <<: *mysql


production_fully_replicated:
  replicated: true
  shards:
    slave1:
      database: octopus_shard2
      <<: *mysql
    slave2:
      database: octopus_shard3
      <<: *mysql
    slave3:
      database: octopus_shard4
      <<: *mysql
    slave4:
      database: octopus_shard5
      <<: *mysql

octopus_rails:
  replicated: true
  verify_connection: true
  environments:
    - staging
    - production

  staging:
    slave1:
      database: octopus_shard2
      <<: *mysql
    slave2:
      database: octopus_shard3
      <<: *mysql

  production:
    slave3:
      database: octopus_shard4
      <<: *mysql
    slave4:
      database: octopus_shard5
      <<: *mysql

not_entire_sharded:
  entire_sharded: false
  shards:
    europe:
      database: octopus_shard2
      <<: *mysql
    canada:
      database: octopus_shard3
      <<: *mysql
    brazil:
      database: octopus_shard4
      <<: *mysql
    russia:
      database: octopus_shard5
      <<: *mysql

modify_config:
  replicated: true
  shards:
    modify_config_read:
      adapter: modify_config
      database: octopus_shard1
      host: localhost
